24h volume feature
MrPaschenko/op-course-work pull request #10
Opened 2021-03-31 18:42 UTC by ILabiak

added 24hour currency volum feature

2021-03-31 19:49 UTC, NeptunePurpleHeart requested changes
Вместо двух запросов на ввод лучше использовать один. Данные из строки можно достать через .split().

2021-03-31 20:10 UTC, akaeyuhi commented on api.js
> +    const query = this.defaultUrl + `/v2/histoday?fsym=${currency}&tsym=${volumeCurrency}&limit=1`;
Нужно сократить строку до 80

2021-03-31 20:10 UTC, akaeyuhi commented on api.js
> +    const volumeCurrency = await question(volCurrText);
Вместо двух запросов лучше объединить в их один и получить из него ответ через .split() и деструктурирующее присвоение

2021-03-31 20:10 UTC, NeptunePurpleHeart commented on api.js
> +      if (priceDiff > 0) {
Вместо if использовать тернарный оператор, это займет меньше места

2021-04-01 12:52 UTC, ILabiak commented on api.js
> +    const query = this.defaultUrl + `/v2/histoday?fsym=${currency}&tsym=${volumeCurrency}&limit=1`;
Пофиксил, строка теперь меньше 80 символов

2021-04-01 12:52 UTC, ILabiak commented on api.js
> +      if (priceDiff > 0) {
Заменил if else на тернарный оператор

2021-04-01 13:13 UTC, NeptunePurpleHeart commented on api.js
> +  async currencyPriceVolume() {
В дальнейшем нужно будет избавиться от огромного количества переменных

2021-04-01 13:13 UTC, NeptunePurpleHeart approved these changes

2021-04-01 13:13 UTC, merged